### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by KeithMoyer** [intel/sgx-cpu-feature-detection#1]
I am interested in this library, but there is no license included to consider whether or not I could include it in a project. Please add an appropriate (preferably permissive - e.g., Apache, BSD) license file to the repository.

**Comment by jmechalas** [comment]
Thank you for pointing out this oversight. For some reason, I forgot to add the LICENSE file to the repo. :( That's been fixed.

This package is covered by the BSD 3-Clause license.
